version: 0.2

phases:
  build:
    commands:
      - echo "Building the application..."
      - zip -r healthcare-app.zip .
      - echo "Listing files in the current directory:"
      - ls -l
      - aws s3 cp healthcare-app.zip s3://healthcare-app-deploy/

artifacts:
  files:
    - healthcare-app.zip
  discard-paths: yes
